# Generated by Django 4.1.1 on 2022-11-25 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ims_inventory', '0002_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0.0)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ims_inventory.inventory')),
            ],
        ),
    ]
